export const thingsILove = [
  "I love when you twirl around like a ballerina.",
  "I love that you have the most beautiful eyes I’ve ever seen.",
  "I love that you have made me a better version of myself.",
  "I love how HOT you are!.",
  "I love how you make me laugh, like, really laugh.",
  "I love you for being my best friend as well as my lover.",
  "I love how it feels like everything is perfect when you lay on my chest.",
  "I love that I can trust you so blindly.",
  "I love how amazing you are with our little animals.",
  "I love how smart you are, I'm always learning from you.",
  "I love how you are constantly taking steps to better yourself.",
  "I love how you look at me.",
  "I love hugging you. Our hugs are the best.",
  "I love how we can do anything that we decide to do together.",
  "I love how crazy you are about making you planner with the little tape and everything.",
  "I love you for how you support me through all of these crazy ideas that I have.",
  "I love our evening walks with young Hank.",
  "I love meal prep Sundays with you, and I love the food we make",
  "I love that you can be so adorable and somehow also so sexy. You got it all.",
  "I love when you let me be there for you.",
  "I love thinking about you and then getting to see you.",
  "I love it when I dream about you then get to wake up next to you.",
  "I love it when you hold on to one of my fingers.",
  "I love staring into your beautiful blue eyes.",
  "I love how excited you were to show me your pottery creations.",
  "I love dancing with you, both slow and grinding.",
  "I love how after years you still give me butterflies.",
  "I love living with you, it's changed my life for the better.",
  "I love how nice you are to my friends, especially Des.",
  "I love how you have your own style and are always changing it to stay fresh.",
  "I love that you accept me for who I am, even knowing my flaws.",
  "I love how you are so patient with me.",
  "I love how you take care of me when I'm sick.",
  "I love it how you get excited about cooking me things.",
  "I love snuggling with you.",
  "I love how much we have in common",
  "I love how you sleep with your arms above your head",
  "I love that we have differences and the way we can accept and respect them",
  "I love when you compliment me",
  "I love going out with you",
  "I love how we split meals at restaurants",
  "I love hearing you sing.",
  "I love that we are best friends",
  "I love how you can always make my day",
  "I love how I still miss you all the time",
  "I love when you post pics of us or the pets to the internet.",
  "I love how much you believe in me.",
  "I love your name.",
  "I love how you want to show me all the Polish things.",
  "I love showing you all the Colombian things.",
  "I love hearing about your day.",
  "I love how much you love animals.",
  "I love traveling the world with you.",
  "I love the sacrifices you've made for us.",
  "I love adventure time with you.",
  "I love that you felt like home when we were in Kenya.",
  "I love how hard you've worked to get where you are.",
  "I love how I admire you.",
  "I love hearing about your childhood.",
  "I love hearing stories about your grandma.",
  "I love putting my arms around you",
  "I love when you put your arms around me",
  "I love when you tell me you love me in different languages",
  "I love when you tell me you love me",
  "I love how affectionate you are.",
  "I love the way you spoil me",
  "I love how you always make my birthday amazing",
  "I love flirting with you",
  "I love talking to you about our future",
  "I love your grit and resiliency",
  "I love how you listen to me talk about my stupid podcasts",
  "I love that you let me listen to whatever music around you",
  "I love when you surprise me",
  "I love how you never let me down",
  "I love how you love old people",
  "I love when you flip out when my hands are cold",
  "I love how you appreciate when I do things for you",
  "I love getting your input",
  "I love kissing you",
  "I love catching up with you after a long day",
  "I love how you brag about me",
  "I love bragging about you",
  "I love how Coloring Book always reminds me of you",
  "I love trying new things with you",
  "I love how we've managed to overcome adversity together",
  "I love how you interact with my mom",
  "I love how you are with all of my family",
  "I love laughing about what crazy parents we will be",
  "I love how I can depend on you for anything",
  "I love that you can be yourself around me",
  "I love your sense of adventure",
  "I love your willingness to try new things",
  "I love how you let me get my sleep",
  "I love being yours",
  "I love how excited you can get over planning",
  "I love how we always balance everything so it's as fair as possible",
  "I love how beautiful you are.",
  "I love how you like to change up your hair",
  "I love you more than I did yesterday",
  "I love how loyal you are",
  "I love how strong you are",
  "I love your laugh",
  "I love learning new things about you",
  "I love when you leave me messages on the whiteboard"
];
